name: kyo_base
description: Kyo base code.
version: 1.0.2+2
publish_to: https://github.com/chihuy105/kyo_base
homepage: https://github.com/chihuy105/kyo_base

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  #  shared_preferences: ^2.0.5
  get: ^4.6.3
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.1.3+1

  ## Network
  retrofit: ^3.0.1
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  synchronized: ^3.0.0
  retry: ^3.1.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  #  rxdart: ^0.27.3

  ## Data format & Json format
  json_serializable: ^6.1.5
  equatable: ^2.0.3
  json_annotation: ^4.4.0

  #####  View
  cupertino_icons: ^1.0.3
  velocity_x: ^3.3.0
  like_button: ^2.0.2
  overlay_support: ^2.0.0
  photo_view: ^0.13.0
  dotted_line: ^3.1.0
  dotted_border: ^2.0.0+2
  animated_text_kit: ^4.1.1
  swipe_cards: ^1.0.0
  flutter_local_notifications: ^9.4.0
  flutter_reaction_button: ^2.0.0+1
  share_plus: ^4.0.1
  flutter_html: ^2.2.1
  flutter_math_fork: ^0.6.1
  tab_indicator_styler: ^2.0.0
  flutter_advanced_segment: ^3.0.0
  pinput: ^1.2.2
  flutter_countdown_timer: ^4.1.0
  readmore: ^2.1.0
  modal_bottom_sheet: ^2.0.1
  infinite_scroll_pagination: ^3.1.0
  visibility_detector: ^0.3.3
  pie_chart: ^5.3.0
  flutter_linkify: ^5.0.2
  swipe_to: ^1.0.2
  scroll_to_index: ^3.0.1
  flutter_staggered_grid_view: ^0.6.1
  screenshot: ^1.2.3
  smooth_page_indicator: ^1.0.0+2
  expandable_page_view: ^1.0.14

  ## Form
  reactive_forms: ^13.0.0
  #  reactive_raw_autocomplete: ^0.1.1
  #  flutter_typeahead: ^3.2.5
  reactive_flutter_typeahead: ^0.4.0
  reactive_range_slider: ^0.4.0

  ## Loading process
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  pull_to_refresh: ^2.0.0
  custom_refresh_indicator: ^1.1.1
  stop_watch_timer: ^1.3.1

  ## Animation
  animate_do: ^2.1.0
  scrollable_positioned_list: ^0.3.2

  ## WebView
  webview_flutter: ^3.0.4
  #  flutter_webview_plugin: ^0.4.0
  #  flutter_inappwebview: ^5.3.2

  ## Navigation
  auto_route: ^4.0.1
  uni_links: ^0.5.1

  #####  Data
  intl: ^0.17.0
  hive: ^2.0.2
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  timeago: ^3.2.2
  url_launcher: ^6.1.0
  email_validator: ^2.0.1
  flutter_multi_formatter: ^2.5.1
  logger: ^1.1.0

  #####  Resource & Config
  flutter_keyboard_visibility: ^5.1.0
  connectivity_plus: ^2.2.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.0
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  package_info_plus: ^1.3.0
  device_info_plus: ^3.2.2
  permission_handler: ^9.2.0
  path: ^1.8.1
  flutter_downloader: ^1.7.4
  path_provider: ^2.0.10
  android_path_provider: ^0.3.0
  flutter_rating_bar: ^4.0.1

  ##### Google Service
  google_place: ^0.4.7
  google_maps_flutter: ^2.1.4
  map_launcher: ^2.2.1+1
  geolocator: ^8.2.0
  geocoding: ^2.0.4

  #####  Firebase
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.10
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.3.4
  firebase_crashlytics: ^2.7.1
  crypto: ^3.0.1
  sign_in_with_apple: ^4.0.0

#dependency_overrides:
#  webview_flutter: ">=3.0.4"
#  flutter_svg: ">=1.1.1+1"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.0.6
  retrofit_generator: ^4.0.1
  flutter_gen_runner: ^4.1.5
  hive_generator: ^1.0.1
  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  test: ^1.19.5
  bloc_test: ^9.0.3

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    null_safety: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

